data:
  image_folder: "../data/preprocess_224_224"
  metadata_path: "../data/pneumonia_dataset_with_metadata.csv"
model:
  input_size: [3, 224, 224]
  num_classes: 2
  resnet_version: 18  # 18, 34, 50, 101, 152
training:
  batch_size: 32
  learning_rate: 1.0e-4
  logs_folder: "../logs/"
  max_epochs: 100
  patience: 10
  transfer_learn: true
inference:
  checkpoint_path: "../logs/lightning_logs/version_122/checkpoints/epoch=04-val_roc-auc=0.895.ckpt"
  shuffle: True
  limit_load_size: 4000  # for quick prototyping. To limit loading images from test dataset to the first 0 to limit_load_size
  predict_size: 100      # batch size for prediction
