data:
  image_folder: "../data/preprocess_224_224"
  metadata_path: "../data/pneumonia_dataset_with_metadata.csv"
model:
  input_size: [3, 224, 224]
  num_classes: 2
  resnet_version: 18  # 18, 34, 50, 101, 152
training:
  batch_size: 32
  learning_rate: 1.0e-4
  logs_folder: "../logs/"
  max_epochs: 100
  patience: 10
  transfer_learn: true
inference:
  checkpoint_path: "../logs/lightning_logs/version_124/checkpoints/epoch=06-val_roc-auc=0.901.ckpt"
  result_folder: "../logs/shifts/"
  test_dataset_size: 4003
  sample_size: 400  # number of samples to use for each run
  batch_size: 32
  embedding_size: 512
  alpha: 0.05 # significance level
plot:
  csv_path: "../logs/shifts/tf_signal_vs_rocauc_compiled.csv"
